const app = {
	NEXT_API_KEY_ETHERSCAN: process.env.NEXT_PUBLIC_API_KEY_ETHERSCAN,
	NEXT_PUBLIC_TARGET_CHAIN_ID: process.env.NEXT_PUBLIC_TARGET_CHAIN_ID,
	NEXT_PUBLIC_NETWORK_ID: process.env.NEXT_PUBLIC_NETWORK_ID,
	NEXT_ETHERSCAN_BASE_URL: process.env.NEXT_PUBLIC_ETHERSCAN_BASE_URL,
	FETCH_INTERVAL_LAST_BLOCK: process.env.NEXT_PUBLIC_FETCH_INTERVAL_LAST_BLOCK,
	FETCH_INTERVAL_ETH_PRICE: process.env.NEXT_PUBLIC_FETCH_INTERVAL_ETH_PRICE,
};

export default app;
